const dataListTeam = [
    {
        id: 1,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 2,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 4,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 3,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 2,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 4,
        name: 'TĐLT',
        fullName: 'Tập đoàn Lương thị',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 3,
        address: 'Hà Nội',
        rank: 6,
        rate: 2,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 5,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 6,
        name: 'TĐLT',
        fullName: 'Tập đoàn Lương thị',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 7,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 8,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 9,
        name: 'TĐLT',
        fullName: 'Tập đoàn Lương thị',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 10,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 11,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
    {
        id: 12,
        name: 'ALV',
        fullName: 'Aliviet',
        slogan: 'Master your self. Master your enemy',
        member: 6,
        createDate: 1539071376000,
        gameId: 1,
        address: 'Hà Nội',
        rank: 3,
        rate: 5,
        avatar: '/static/images/home/demacia.jpg'
    },
];
export default dataListTeam;