branch-defaults:
  dev:
    environment: staging
    group_suffix: null
  feature/ci:
    environment: staging
    group_suffix: null
  master:
    environment: timkeo-client-ssr-prod-2
    group_suffix: null
global:
  application_name: timkeo-client-ssr
  branch: null
  default_ec2_keyname: timkeo
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
