const dataGamesChallenge = [
    {
        id: 1,
        name: 'lol',
        count: 10,
        challenges: {
            online: [
                {
                    teamId: 1,
                    team: 'ALV',
                    fullName: 'Aliviet',
                    slogan: 'Master your self. Master your enemy',
                    rate: 5,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 500000,
                    status: 3,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 2,
                    team: 'TĐLT',
                    fullName: 'Tập đoàn Lương thị',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 2000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 3,
                    team: 'CN100',
                    fullName: 'Cô lô nhuê',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 200000,
                    status: 1,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 4,
                    team: 'Sphinx',
                    fullName: 'Sphinx Company',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 1000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
            ],
            offline: [
                {
                    teamId: 6,
                    team: 'ALV',
                    fullName: 'Aliviet',
                    slogan: 'Master your self. Master your enemy',
                    rate: 5,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 500000,
                    status: 3,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 7,
                    team: 'TĐLT',
                    fullName: 'Tập đoàn Lương thị',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 2000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 8,
                    team: 'CN100',
                    fullName: 'Cô lô nhuê',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 200000,
                    status: 1,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 9,
                    team: 'Sphinx',
                    fullName: 'Sphinx Company',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 1000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
            ]
        }
    },
    {
        id:2,
        name: 'fo4',
        count: 10,
        challenges: {
            online: [
                {
                    teamId: 1,
                    team: 'ALV',
                    fullName: 'Aliviet',
                    slogan: 'Master your self. Master your enemy',
                    rate: 5,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 500000,
                    status: 3,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 2,
                    team: 'TĐLT',
                    fullName: 'Tập đoàn Lương thị',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 2000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 3,
                    team: 'CN100',
                    fullName: 'Cô lô nhuê',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 200000,
                    status: 1,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 4,
                    team: 'Sphinx',
                    fullName: 'Sphinx Company',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 1000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
            ],
            offline: [
                {
                    teamId: 6,
                    team: 'ALV',
                    fullName: 'Aliviet',
                    slogan: 'Master your self. Master your enemy',
                    rate: 5,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 500000,
                    status: 3,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 7,
                    team: 'TĐLT',
                    fullName: 'Tập đoàn Lương thị',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 2000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 8,
                    team: 'CN100',
                    fullName: 'Cô lô nhuê',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 200000,
                    status: 1,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 9,
                    team: 'Sphinx',
                    fullName: 'Sphinx Company',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 1000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
            ]
        }
    },
    {
        id:3,
        name: 'aoe',
        count: 10,
        challenges: {
            online: [
                {
                    teamId: 1,
                    team: 'ALV',
                    fullName: 'Aliviet',
                    slogan: 'Master your self. Master your enemy',
                    rate: 5,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 500000,
                    status: 3,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 2,
                    team: 'TĐLT',
                    fullName: 'Tập đoàn Lương thị',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 2000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 3,
                    team: 'CN100',
                    fullName: 'Cô lô nhuê',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 200000,
                    status: 1,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 4,
                    team: 'Sphinx',
                    fullName: 'Sphinx Company',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 1,
                    mode: 5,
                    rank: 3,
                    betting: 1000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
            ],
            offline: [
                {
                    teamId: 6,
                    team: 'ALV',
                    fullName: 'Aliviet',
                    slogan: 'Master your self. Master your enemy',
                    rate: 5,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 500000,
                    status: 3,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 7,
                    team: 'TĐLT',
                    fullName: 'Tập đoàn Lương thị',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 2000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 8,
                    team: 'CN100',
                    fullName: 'Cô lô nhuê',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 200000,
                    status: 1,
                    avatar:'/static/images/home/demacia.jpg'
                },
                {
                    teamId: 9,
                    team: 'Sphinx',
                    fullName: 'Sphinx Company',
                    slogan: 'Master your self. Master your enemy',
                    rate: 4,
                    time: 1539071376000,
                    kind: 0,
                    address:'Level Esport Gaming',
                    mode: 5,
                    rank: 3,
                    betting: 1000000,
                    status: 0,
                    avatar:'/static/images/home/demacia.jpg'
                },
            ]
        }
    }
];

export default dataGamesChallenge;